apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: database-credentials
  namespace: my-application
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "false"
spec:
  encryptedData:
    # These values are encrypted with the SealedSecrets controller's public key
    # and can only be decrypted by the controller running in the target cluster
    username: AgBy8hCG9p5PypLoCXfUKTVeFY2BFR5fQJYZgxbLKGD7c5JVv6kWM5K1V57DbsZnu9WIZ+KasMGgpzL0JG/q3Z95n8BLRA9i11nGQa5VcIJ67QO1Xs5NvTxiK0oW57LicOPZj6grIIBrqvNNynH2ABLxhW1h
    password: AgCZJUA7RKhpkY56H5qNQJgWy1tY0A9tJ0dfUh8eL8jLb2LBLyNDqbBjW5VuHQBgV/K+HF0TYc1/3VJnrJ4V/G+3mX2rvw9PZfZQ8shHHA
    host: AgAr1BLqm3nXbGq/eE/EjdQcjGXJ7j2D1aUvzBLLSRB9ksQYU3UlA1hxPEyNGAxhbYTD7tzZ65s8fUvxfT0VhiVH3jnS+ABUgUdmvSw0/0IZR7A+BkWMb4KSk9ij+YqTmQ==
    port: AgCjrrDqYPtb7bqsXl9XF7DTmLTjhAPvSvzxLdU7TgI0dkSn3RQvZc1CxOtpjNYyfnVxRXJdw+YLPRpz+fQ9UwvLCqcg
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-keys
  namespace: my-application
spec:
  encryptedData:
    stripe-api-key: AgCElWH52PSlh5RdODvLV23nt89Z0LKLbQf+3zNZfPSPT7qrOh0S+MkL/yGHuC/TZY8JKzJqK8bE0P+1k2V3abG39KJWw/ew
    sendgrid-api-key: AgB7bHnS0Nc0yIrWVGCmXm8Q51viIPNX+cB90K1z8zs1Z2X5GRqwfvUIlEnTeDGVc0vqv6rnqHIp46NMHnkuKA==
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tls-certificate
  namespace: my-application
spec:
  encryptedData:
    tls.crt: AgA9xKz8EQxLiGEr0Fvd+vS0HVkZH/oQ6qC0gBguzgSyAUTbQ+eCKVJoXvF31S9kGAZ2Jh60wVnkLTHJbK5dLbmRs+G+gEJBrqv2d5Gj2JyXaC+4S8kLYZK+MzcvrPm3R5Bdd5AufO7g2Uq5hjUdIzg5vPJ22KF+oHgjKqA0J2NFDYQL2IQGKMaVfbgw3HgKlWdFNvPE6G+9/n6jB+K9EWkMGJl7
    tls.key: AgB9wZdTT2QH9LuKqjJ5vWUkQtWrn6J2m1JnvS+C6P6wGcZPPq82NwH0M5x3Jq/F7KQlfLH0+nCnkGCwffK5S+3Pr5eEEd0lGP/r2w7p5ScLgxCcZeBvDhbgNCXo3qfCX4lI6QnSEhQrb8DqWb/HQ1XblXP3K4V5
