name: Policy Validation

on:
  push:
    branches: [ main ]
    paths:
      - 'policy/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'policy/**'

jobs:
  opa-validate:
    name: Validate OPA Policies
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup OPA
      run: |
        curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
        chmod 755 ./opa
        sudo mv ./opa /usr/local/bin/opa
        opa version
    
    - name: Find Rego files
      id: find-rego
      run: |
        REGO_FILES=$(find policy -name "*.rego" -type f | tr '\n' ' ')
        if [ -z "$REGO_FILES" ]; then
          echo "No Rego files found to validate"
          exit 0
        fi
        echo "REGO_FILES=${REGO_FILES}" >> $GITHUB_ENV
    
    - name: Validate Rego files
      if: env.REGO_FILES != ''
      run: |
        set -e
        for file in $REGO_FILES; do
          echo "Validating Rego file: $file"
          opa check $file
        done
